# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# Automatically Detect Projects
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Find .NET projects
      run: |
        echo "projects=$(find . -name '*.csproj' -exec dirname {} \; | sort | uniq | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Restore, Build and Test Projects
      run: |
        for project in $projects; do
          echo "Processing $project..."
          dotnet restore "$project"
          dotnet build "$project" --no-restore
          dotnet test "$project" --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --collect "Code Coverage"
        done

    - name: Display Test Results
      run: find . -name 'test-results.trx' -exec cat {} \;

    - name: Generate Coverage Report
      run: |
        coverage_files=$(find . -name 'coverage.cobertura.xml' | tr '\n' ';')
        if [ -z "$coverage_files" ]; then
          echo "No coverage reports found. Skipping report generation."
          exit 0
        fi
        reportgenerator -reports:"$coverage_files" -targetdir:coverage-report -reporttypes:HtmlInline_AzurePipelines


    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/TestResults/*.trx"

    - name: Upload Code Coverage Results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: "**/TestResults/**/coverage.cobertura.xml"

    - name: Upload Human-Readable Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report
